package com.wjw.blog.dao;

import java.util.List;

import com.wjw.blog.entity.aritcletype;

public interface aritcletypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcletype
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcletype
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insert(aritcletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcletype
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insertSelective(aritcletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcletype
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    aritcletype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcletype
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKeySelective(aritcletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcletype
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKey(aritcletype record);
    
    
    List<aritcletype> getAllaritcletype();
}