package com.wjw.blog.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wjw.blog.entity.aritcle;

public interface aritcleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcle
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcle
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insert(aritcle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcle
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insertSelective(aritcle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcle
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    aritcle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcle
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKeySelective(aritcle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_aritcle
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKey(aritcle record);
    
    //获取所有文章信息
    List<aritcle>getAllaritcles(@Param(value="begin") int begin,@Param(value="PageSize") int PageSize,@Param(value="typeid") int typeid);
    
    //所有文章数量
    int getCount(@Param(value="typeid") int typeid);
    
    //删除评论时减少评论数量
    int DelCommentNum(int id);
}