package com.wjw.blog.dao;

import java.util.List;
import java.util.function.Consumer;

import org.apache.ibatis.annotations.Param;

import com.wjw.blog.entity.consumer;

public interface consumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_consumer
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_consumer
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insert(consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_consumer
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insertSelective(consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_consumer
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    consumer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_consumer
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKeySelective(consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_consumer
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKey(consumer record);
    
    List<consumer>getAllConsumer();
 
    int login(@Param(value = "account") String account,@Param(value="password") String password);
    
    consumer userlogin(@Param(value = "account") String account,@Param(value="password") String password);
}