package com.wjw.blog.dao;

import com.wjw.blog.entity.news;

public interface newsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insert(news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insertSelective(news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    news selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKeySelective(news record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_news
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKey(news record);
}