package com.wjw.blog.dao;

import com.wjw.blog.entity.photo;

public interface photoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insert(photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int insertSelective(photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    photo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKeySelective(photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    int updateByPrimaryKey(photo record);
}