package com.wjw.blog.entity;

import java.util.Date;

public class aritcle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.typeId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.title
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.content
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.phTime
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Date phtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.number
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.summary
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_aritcle.sign
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.id
     *
     * @return the value of tb_aritcle.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.id
     *
     * @param id the value for tb_aritcle.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.typeId
     *
     * @return the value of tb_aritcle.typeId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.typeId
     *
     * @param typeid the value for tb_aritcle.typeId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.title
     *
     * @return the value of tb_aritcle.title
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.title
     *
     * @param title the value for tb_aritcle.title
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.content
     *
     * @return the value of tb_aritcle.content
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.content
     *
     * @param content the value for tb_aritcle.content
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.phTime
     *
     * @return the value of tb_aritcle.phTime
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Date getPhtime() {
        return phtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.phTime
     *
     * @param phtime the value for tb_aritcle.phTime
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setPhtime(Date phtime) {
        this.phtime = phtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.number
     *
     * @return the value of tb_aritcle.number
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.number
     *
     * @param number the value for tb_aritcle.number
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.summary
     *
     * @return the value of tb_aritcle.summary
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.summary
     *
     * @param summary the value for tb_aritcle.summary
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_aritcle.sign
     *
     * @return the value of tb_aritcle.sign
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_aritcle.sign
     *
     * @param sign the value for tb_aritcle.sign
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}