package com.wjw.blog.entity;

import java.util.Date;

public class comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.authorId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
   // private Integer authorid;

    private consumer consumer;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.aritcleId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
   // private Integer aritcleid;
    private aritcle aritcle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.content
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.time
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.id
     *
     * @return the value of tb_comment.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.id
     *
     * @param id the value for tb_comment.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.authorId
     *
     * @return the value of tb_comment.authorId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
/*    public Integer getAuthorid() {
        return authorid;
    }*/
    public consumer getConsumer() {
    	return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.authorId
     *
     * @param authorid the value for tb_comment.authorId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
/*    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }*/
    public void setConsumer(consumer consumer){
    	this.consumer=consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.aritcleId
     *
     * @return the value of tb_comment.aritcleId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
/*    public Integer getAritcleid() {
        return aritcleid;
    }*/
    public aritcle getAritcle() {
    	return aritcle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.aritcleId
     *
     * @param aritcleid the value for tb_comment.aritcleId
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
/*    public void setAritcleid(Integer aritcleid) {
        this.aritcleid = aritcleid;
    }*/
      public void setAritcle(aritcle aritcle) {
    	  this.aritcle=aritcle;
      }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.content
     *
     * @return the value of tb_comment.content
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.content
     *
     * @param content the value for tb_comment.content
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.time
     *
     * @return the value of tb_comment.time
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.time
     *
     * @param time the value for tb_comment.time
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}