package com.wjw.blog.entity;

public class consumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.account
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.password
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.name
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.sex
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.email
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.phone
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.Isvalid
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer isvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_consumer.master
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer master;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.id
     *
     * @return the value of tb_consumer.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.id
     *
     * @param id the value for tb_consumer.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.account
     *
     * @return the value of tb_consumer.account
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.account
     *
     * @param account the value for tb_consumer.account
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.password
     *
     * @return the value of tb_consumer.password
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.password
     *
     * @param password the value for tb_consumer.password
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.name
     *
     * @return the value of tb_consumer.name
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.name
     *
     * @param name the value for tb_consumer.name
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.sex
     *
     * @return the value of tb_consumer.sex
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.sex
     *
     * @param sex the value for tb_consumer.sex
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.email
     *
     * @return the value of tb_consumer.email
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.email
     *
     * @param email the value for tb_consumer.email
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.phone
     *
     * @return the value of tb_consumer.phone
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.phone
     *
     * @param phone the value for tb_consumer.phone
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.Isvalid
     *
     * @return the value of tb_consumer.Isvalid
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.Isvalid
     *
     * @param isvalid the value for tb_consumer.Isvalid
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_consumer.master
     *
     * @return the value of tb_consumer.master
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_consumer.master
     *
     * @param master the value for tb_consumer.master
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setMaster(Integer master) {
        this.master = master;
    }
}