package com.wjw.blog.entity;

import java.util.Date;

public class photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.name
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.description
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.url
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.album_id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Integer albumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo.time
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.id
     *
     * @return the value of tb_photo.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.id
     *
     * @param id the value for tb_photo.id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.name
     *
     * @return the value of tb_photo.name
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.name
     *
     * @param name the value for tb_photo.name
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.description
     *
     * @return the value of tb_photo.description
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.description
     *
     * @param description the value for tb_photo.description
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.url
     *
     * @return the value of tb_photo.url
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.url
     *
     * @param url the value for tb_photo.url
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.album_id
     *
     * @return the value of tb_photo.album_id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.album_id
     *
     * @param albumId the value for tb_photo.album_id
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo.time
     *
     * @return the value of tb_photo.time
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo.time
     *
     * @param time the value for tb_photo.time
     *
     * @mbg.generated Sun Jan 13 14:05:29 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}